### ISSUE TITLE
Get this on melpa?

### ISSUE THREAD

**Issue by expez** [shaunxcode/el-edn#1]
I need an edn lib for elisp and this seems to fit the bill.  I notice there aren't any tests, would you consider this ready for general consumption?  If so, any interesting in packaging this for melpa?

**Comment by shaunxcode** [comment]
That is a good question/idea - I had all but forgotten about this until you starred the project! There are a suite of tests here https://github.com/shaunxcode/edn-tests which would be a good way of proving things are correct by adding the el-edn platform. I do not currently have the time but you are more than welcome to fork/put into melpa etc.

**Comment by expez** [comment]
Gave `el-edn` a try, `(edn-parse "#{:on :sets}"` doesn't work.

I also generated a [test suite](https://gist.github.com/expez/3e06ad340a306d11bedc): 

```
Selector: t
Passed:  31
Failed:  21 (21 unexpected)
Skipped: 0
Total:   52/52
```

There's quite a bit of:

```
F comment
    (error "unknown type for ;;comment")

F comment-trailing
    (error "unknown type for valid;touching")

F discard-entire-form
    (void-function nil)

F discard-in-vector
    (void-function nil)

F discard-outside-form
    (void-function nil)

F discard-touching-item
    (void-function nil)

F discard-with-comment
    (error "unknown type for ;we")
```

and 
```
F whitespace-blank
    (wrong-type-argument hash-table-p nil)

F whitespace-comma
    (wrong-type-argument hash-table-p nil)

F whitespace-single-space
    (wrong-type-argument hash-table-p nil)

F whitespace-triple-space
    (wrong-type-argument hash-table-p nil)
```

Which indicate quite a few tests might start passing by fixing one or two problems.

**Comment by expez** [comment]
The changes below made sets work.  I'd submit a PR but I'm not sure if this speaks to problems elsewhere or not.

```diff
@@ -145,8 +145,12 @@
 	    (t 'EdnTagged))
       (gethash 'line token)
       (let ((content (make-hash-table :test 'equal)))
-	(puthash 'tag (edn-node 'EdnSymbol (gethash 'line token) tag-name) content)
-	(puthash 'value value content)
+       (if (string-equal tag-name "")
+           (progn (puthash 'type 'EdnSet content)
+                  (puthash 'value (gethash 'value value) content))
+         (progn (puthash 'tag (edn-node 'EdnSymbol (gethash 'line token) tag-name) content)
+                (puthash 'value value content)))
+
 	content))))
 
 (defun lex (edn-string)
@@ -309,12 +309,13 @@
          (handler (or (gethash tag edn-tag-handlers) (lambda (val) value))))
     (funcall handler val)))
 
-
 (defun edn-reify (node)
   (let* ((type (gethash 'type node))
          (value (gethash 'value node)))
     (when (node-is-collection node)
-      (setq value (mapcar 'edn-reify value)))
+      (if (listp value)
+          (setq value (mapcar 'edn-reify value))
+        (setq value (edn-reify value))))
     (if (eq type 'EdnTagged)
         (reify-tagged value)
         (funcall (gethash type edn-reify-handlers) value))))
```

**Comment by expez** [comment]
I generated a test-suite using the `edn-tests` and I now have the following fixes in [my fork](https://github.com/expez/el-edn/commits/master):
- Eliding forms (using the #_ reader macro)
- Reading only whitespace returns `nil` instead of crashing
- Comment parsing works correctly
- Replaced some homemade string functions with `s.el` (I'm planning more)
- Namespaced all functions (`edn--` prefix for private, `edn-` prefix for rest)
- Fix edn-parse for sets

I'd like to contribute these changes back, but what I'd like the most is if you'd be willing to move this repo over to the [clojure-emacs](https://github.com/clojure-emacs) organization.  This will increase visibility and you'll get a few more people fixing bugs and closing issues :)

I have some other use-cases in mind, but I'd like to use this when moving data from [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl) to [clj-refactor](https://github.com/clojure-emacs/clj-refactor.el).
